#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
# Gradle start up script for POSIX generated by "Gradle init".

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Attempt to find JAVA_HOME
if [ -z "$JAVA_HOME" ] ; then
    if [ -r /etc/gentoo-release ] ; then
        JAVA_HOME=`java-config --jre-home`
    fi
fi

# Determine script directory
cd "`dirname \"$0\"`" >/dev/null
APP_HOME="`pwd -P`"
cd "`dirname \"$0\"`" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Execute Gradle
exec "$JAVA_HOME/bin/java" $DEFAULT_JVM_OPTS \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
